[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tyru/caw.vim'
rev = 'master'

[[plugins]]
repo = 'altercation/vim-colors-solarized.git'

[[plugins]]
repo = 'mattn/emmet-vim.git'

[[plugins]]
repo = 'othree/eregex.vim.git'

[[plugins]]
repo = 'thinca/vim-quickrun.git'

[[plugins]]
repo = 'thinca/vim-ref.git'

[[plugins]]
repo = 'tpope/vim-repeat.git'

[[plugins]]
repo = 'tpope/vim-surround.git'

[[plugins]]
repo = 'jceb/vim-hier'

[[plugins]]
repo = 'qtmplsel.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'vimtaku/hl_matchit.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'Chiel92/vim-autoformat'

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'Shougo/denite.nvim'
