#!/bin/bash -u

#============================
# SUB ROUTINE
#============================

usage_exit()
{
  echo "Usage: $0" >&2
  exit 1
}

print_div()
{
  echo "--------------------------------------------------------------------------------"
}

print_fence() 
{
  print_div
  echo -e  "   $1 : $2 ($SECONDS sec)"
  print_div
}

prep_dir()
{
  if [ ! -e $1 ]; then
    echo "[$0] mkdir $1"
    mkdir -p $1
  fi
}

#============================
# VARIABLES
#============================
SCRIPT_DIR=$(cd $(dirname ${BASH_SOURCE}); pwd)
RANDNAME=$(cat /dev/urandom | tr -dc [:alnum:] | head -c 15)

#============================
# MAIN ROUTINE
#============================
# 0. setup
if [ $# -ne 0 ]; then
  usage_exit
fi
